apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my
  namespace: argocd
spec:
  project: campaigns-proj1
  source:
    path: squad-proj/projs/campaigns-proj1/my/
    repoURL: https://github.com/arjundandagi/chartautomation.git
    targetRevision: HEAD
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
