apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: campaigns
  source:
    path: stg-eu/apps/helm/
    repoURL: https://github.com/arjundandagi/chartautomation.git
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
