apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: app1
  source:
    path: stg-eu/apps/
    repoURL: https://github.com/arjundandagi/chartautomation.git
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
