apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd #can't create application in a different namespace 
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default   #root apps can go in the default project 
  source:
    path: stg-eu/apps
    repoURL: https://github.com/arjundandagi/chartautomation
    targetRevision: HEAD
