apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hk
  namespace: argocd
spec:
  project: cart-proj
  source:
    path: squad-proj/projs/cart-proj/hk.yml
    repoURL: https://github.com/arjundandagi/chartautomation.git
    targetRevision: HEAD
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
